name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]  # Set a branch to deploy

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python3 -m pip install sphinx

    - name: Build documentation
      run: |
        python3 main.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
